<?php
return [
    'views' => 'panel::panel-inspinia',
    'layout' => 'layouts.app',
    'date' => [
        'format' => 'm/d/Y',
    ],
    'labels' => [
        'none' => 'panel.labels.none',
        'list-empty' => 'panel.labels.list-empty',
        'move-to' => 'panel.labels.move-to',
        'sort-up' => 'panel.labels.sort-up',
        'sort-down' => 'panel.labels.sort-down',
        'validation-failed' => 'panel.labels.validation-failed',
        'choose' => 'panel.labels.choose',
        'name' => 'panel.labels.name',
        'edit' => 'panel.labels.edit',
        'create' => 'panel.labels.create',
        'filter' => 'panel.labels.filter',
    ],
    'confirm' => [
        'default' => 'panel.confirm.default',
        'move-to' => 'panel.confirm.move-to',
        'delete' => 'panel.confirm.delete',
        'group-delete' => 'panel.confirm.group-delete',
    ],
    'responses' => [
        'success' => 'panel.responses.success',
        'error' => 'panel.responses.error',
    ],
    'actions' => [
        'create' => [
            'class' => 'btn btn-default btn-sm',
            'label' => 'panel.actions.create',
            'action' => 'create',
            'icon' => 'fa fa-file-o',
        ],
        'edit' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.edit',
            'action' => 'edit',
            'icon' => 'fa fa-edit',
            'icon-only' => true,
        ],
        'show' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.show',
            'action' => 'showModel',
            'icon' => 'fa fa-file-o',
            'icon-only' => true,
        ],
        'delete' => [
            'class' => 'btn btn-danger btn-xs',
            'label' => 'panel.actions.delete',
            'action' => 'delete',
            'icon' => 'fa fa-trash-o',
            'icon-only' => true,
            'confirm' => 'panel.confirm.delete',
        ],
        'enable' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.enable',
            'action' => 'enable',
            'icon' => 'fa fa-eye-slash',
            'icon-on-hover' => 'fa fa-eye',
            'icon-only' => true,
        ],
        'disable' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.disable',
            'action' => 'disable',
            'icon' => 'fa fa-eye',
            'icon-on-hover' => 'fa fa-eye-slash',
            'icon-only' => true,
        ],
        'lock' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.unlock',
            'action' => 'unlock',
            'icon' => 'fa fa-lock',
            'icon-on-hover' => 'fa fa-unlock',
            'icon-only' => true,
        ],
        'unlock' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.lock',
            'action' => 'lock',
            'icon' => 'fa fa-unlock',
            'icon-on-hover' => 'fa fa-lock',
            'icon-only' => true,
        ],
        'link' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'Открыть',
            'icon' => 'fa fa-xs fa-external-link',
            'icon-only' => true,
            'target' => '_blank',
        ],
        'append' => [
            'class' => 'btn btn-default btn-xs',
            'label' => 'panel.actions.append',
            'action' => 'create',
            'icon' => 'fa fa-plus',
            'icon-only' => true,
        ],
        'group-enable' => [
            'class' => 'btn btn-default btn-sm',
            'label' => 'panel.actions.group-enable',
            'action' => 'groupEnable',
            'icon' => 'fa fa-eye',
            'icon-only' => true,
        ],
        'group-disable' => [
            'class' => 'btn btn-default btn-sm',
            'label' => 'panel.actions.group-disable',
            'action' => 'groupDisable',
            'icon' => 'fa fa-eye-slash',
            'icon-only' => true,
        ],
        'group-lock' => [
            'class' => 'btn btn-default btn-sm',
            'label' => 'panel.actions.group-lock',
            'action' => 'groupLock',
            'icon' => 'fa fa-lock',
            'icon-only' => true,
        ],
        'group-unlock' => [
            'class' => 'btn btn-default btn-sm',
            'label' => 'panel.actions.group-unlock',
            'action' => 'groupUnlock',
            'icon' => 'fa fa-unlock',
            'icon-only' => true,
        ],
        'group-delete' => [
            'class' => 'btn btn-default btn-sm',
            'label' => 'panel.actions.group-delete',
            'action' => 'groupDelete',
            'icon' => 'fa fa-trash-o',
            'icon-only' => true,
            'confirm' => 'panel.confirm.group-delete',
        ],
        'default' => [
            'class' => 'btn btn-default btn-sm',
        ],

    ],
    'buttons' => [
        'submit' => [
            'class' => 'btn-primary',
            'type' => 'submit',
            'label' => 'panel.buttons.submit',
            'icon' => 'submit',
        ],
        'apply' => [
            'class' => 'btn-primary',
            'type' => 'submit',
            'name' => '_apply',
            'label' => 'panel.buttons.apply',
            'icon' => 'apply',
        ],
        'cancel' => [
            'class' => 'btn-default',
            'type' => 'button',
            'label' => 'panel.buttons.cancel',
            'icon' => 'cancel',
        ],
        'filter' => [
            'class' => 'btn-primary',
            'type' => 'submit',
            'label' => 'panel.buttons.filter',
            'icon' => 'fa fa-filter',
        ],
        'reset' => [
            'class' => 'btn-default',
            'type' => 'button',
            'label' => 'panel.buttons.reset',
            'icon' => 'fa fa-times',
        ],
        'back' => [
            'class' => 'btn-default',
            'type' => 'button',
            'label' => 'panel.buttons.back',
            'icon' => 'fa fa-long-arrow-left',
        ],
        'edit' => [
            'tag-name' => 'a',
            'class' => 'btn-default',
            'type' => 'button',
            'label' => 'panel.buttons.edit',
            'icon' => 'fa fa-edit',
        ],
        'enable' => [
            'tag-name' => 'a',
            'class' => 'btn-default',
            'type' => 'button',
            'label' => 'panel.buttons.enable',
            'icon' => 'fa fa-eye',
        ],
        'disable' => [
            'tag-name' => 'a',
            'class' => 'btn-default',
            'type' => 'button',
            'label' => 'panel.buttons.disable',
            'icon' => 'fa fa-eye-slash',
        ],
        'delete' => [
            'tag-name' => 'a',
            'class' => 'btn-default text-danger',
            'type' => 'button',
            'label' => 'panel.buttons.delete',
            'icon' => 'fa fa-trash-o',
            'confirm' => 'panel.confirm.delete',
        ],
        'default' => [
            'class' => 'btn-default',
            'type' => 'button',
        ],
    ],
];